version: "3.9"
services:
  db:
    image: docker.io/library/postgres:latest
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "${DB_PORT}:${DB_PORT}"
    volumes:
      - db_data:/var/lib/postgresql/data
  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment: 
      DB_HOST: db
      DB_PORT: ${DB_PORT}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_USER}
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}"
    depends_on:
      - db
    security_opt:
      - "label=disable"
volumes:
  db_data:
    driver: local